[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
loglevel=info
stdout_logfile=/var/log/supervisor/supervisord.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisor/supervisord.err
stderr_logfile_maxbytes=0
pidfile=/var/run/supervisor/supervisord.pid 
childlogdir=/var/log/supervisor

[program:nginx]
command=nginx -g 'daemon off;'
user=root
stdout_logfile=/var/log/supervisor/supervisord.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisor/supervisord.err
stderr_logfile_maxbytes=0
autorestart=true
startretries=3
[program:ravage]
directory=/app
command=/app/ravage
user=root
stdout_logfile=/var/log/supervisor/supervisord.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisor/supervisord.err
stderr_logfile_maxbytes=0
autorestart=true
startretries=3

