//! Database schema definitions for the Ravage load testing platform.
//! This module is automatically generated by Diesel CLI and defines the database structure.

// @generated automatically by Diesel CLI.

/// Table for storing collection-level HTTP headers
/// 
/// Headers that apply to all requests within a collection
diesel::table! {
    collection_headers (id) {
        id -> Integer,
        collection_id -> Integer,
        key -> Text,
        value -> Text,
        created_at -> Timestamp,
        updated_at -> Nullable<Timestamp>,
    }
}

/// Table for storing collections of HTTP requests
/// 
/// Collections group related requests together and can have their own headers
diesel::table! {
    collections (id) {
        id -> Integer,
        name -> Text,
        host -> Text,
        created_at -> Timestamp,
        updated_at -> Nullable<Timestamp>,
    }
}

/// Table for storing load test configurations and results
/// 
/// Tracks load test runs and their associated reports and logs
diesel::table! {
    load_tests (id) {
        id -> Integer,
        source_type -> Nullable<Text>,
        source_id -> Nullable<Integer>,
        name -> Text,
        log_path -> Nullable<Text>,
        report_path -> Nullable<Text>,
        created_at -> Timestamp,
        updated_at -> Nullable<Timestamp>,
    }
}

/// Table for storing request-specific HTTP headers
/// 
/// Headers that apply to individual requests
diesel::table! {
    request_headers (id) {
        id -> Integer,
        request_id -> Integer,
        key -> Text,
        value -> Text,
        created_at -> Timestamp,
        updated_at -> Nullable<Timestamp>,
    }
}

/// Table for storing HTTP requests
/// 
/// Defines the structure of HTTP requests that can be used in collections
diesel::table! {
    requests (id) {
        id -> Integer,
        name -> Text,
        collection_id -> Integer,
        path -> Text,
        method -> Text,
        body_type -> Nullable<Text>,
        body_content -> Nullable<Text>,
        created_at -> Timestamp,
        updated_at -> Nullable<Timestamp>,
    }
}

// Define relationships between tables
diesel::joinable!(collection_headers -> collections (collection_id));
diesel::joinable!(request_headers -> requests (request_id));
diesel::joinable!(requests -> collections (collection_id));

// Allow all tables to be used in the same query
diesel::allow_tables_to_appear_in_same_query!(
    collection_headers,
    collections,
    load_tests,
    request_headers,
    requests,
);
